### ISSUE TITLE
Erro de atualização de recurso

### ISSUE THREAD

**Issue by gabrielbdornas** [dados-mg/dpckan#147]
Durante teste da implementação #146 @Andrelamor encontrou o seguinte erro:

```
(venv)
Andre@DESKTOP-R63LP8N MINGW64 ~/Documents/teletrabalho/dados-mg/doacoes-comodatos-amigo-estado-mg (master)
$ dpckan resource update --resource-name doacoes-comodatos-amigo-estado-mg --resource-id 83adf097-d4fe-4d6d-8e36-459c1c43907f
Atualizando recurso: doacoes-comodatos-amigo-estado-mg
Atualizando metadado de recurso: doacoes-comodatos-amigo-estado-mg
Traceback (most recent call last):
  File "C:\Users\Andre\Documents\teletrabalho\dados-mg\dpckan\venv\Scripts\dpckan-script.py", line 33, in <module>
    sys.exit(load_entry_point('dpckan', 'console_scripts', 'dpckan')())
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\dpckan\update_resource.py", line 113, in update_resource_cli
    update_resource(ckan_host, ckan_key, datapackage, resource_id, resource_name, stop)
  File "c:\users\andre\documents\teletrabalho\dados-mg\dpckan\dpckan\update_resource.py", line 59, in update_resource
    datapackage_resource_id = [i["id"] for i in ckan_datapackage_resources if i["name"] == "datapackage.json"][0]
IndexError: list index out of range
```

**Comment by gabrielbdornas** [comment]
Durante a [chamada da api](https://dados.mg.gov.br/api/3/action/package_show?id=doacoes-comodatos-amigo-estado-mg), identifiquei que a propriedade name do recurso datapackage deste conjunto é "datapackage" e não "datapackage.json", conforme proposto no código

![image](https://user-images.githubusercontent.com/49699290/150407073-e2c5bd09-f02e-4e9a-a901-ed78dddaddb7.png)

Sendo assim, deverá ser feito modificação no código para que ele busque o nome do arquivo via propriedade url.

**Comment by fjuniorr** [comment]
> Sendo assim, deverá ser feito modificação no código para que ele busque o nome do arquivo via propriedade url.

Você percebeu que o commit 526496296da9e840a0c5a04ad790891b8097596f você não implementou a extração do nome do arquivo usando a propriedade `url` ?

**Comment by gabrielbdornas** [comment]
@fjuniorr, my foult. Corrected [here](https://github.com/dados-mg/dpckan/commit/744f59fa213fe453a68aad80c22ef2a7b9ab751c).

**Comment by gabrielbdornas** [comment]
Closed after https://github.com/dados-mg/dpckan/pull/146
