### ISSUE TITLE
Erro `ModuleNotFoundError: No module named 'click._bashcomplete'`

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/dpckan#35]
Esse erro que encontramos ontem no `dpckan` também apareceu hoje no [age7](https://github.com/transparencia-mg/age7): 

```python
>>> from pprint import pprint
>>> from frictionless import validate_schema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/frictionless/__init__.py", line 21, in <module>
    from .program import program
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/frictionless/program/__init__.py", line 1, in <module>
    from .api import program_api
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/frictionless/program/api.py", line 1, in <module>
    from typer import Option as Opt
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/typer/__init__.py", line 31, in <module>
    from .main import Typer, run
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/Users/fjunior/Library/r-miniconda/envs/age7/lib/python3.9/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

Ainda não entendi a causa exata nem como corrigir, mas achei o issue relevante https://github.com/tiangolo/typer/issues/280.

**Comment by fjuniorr** [comment]
Coloquei uma mensagem no [Discord](https://discord.com/channels/695635777199145130/695635777199145133/860250148373921812) da Frictionless pra ver se mais alguém tá enfrentando esse problema.

**Comment by gabrielbdornas** [comment]
fechado com o [PR](https://github.com/dados-mg/dpckan/pull/34)
